#!/usr/bin/python3
from sys import argv, exit


def main():
    if len(argv) != 2:
        print("factors <file>")
        exit(-1)
    with open(argv[1], "r") as f:
        line = f.readline()
        while line:
            number = int(line.strip())
            print_factors(number)
            line = f.readline()


def print_factors(number):
    i = 2
    while number % i:
        i += 1
    print("{}={}*{}".format(number, number // i, i))


if __name__ == "__main__":
    main()
